### ISSUE TITLE
The Makefile (system) is very unfriendly for OS packagers and arguably broken

### ISSUE THREAD

**Issue by fenrus75** [intel/QAT-ZSTD-Plugin#6]
The makefiles do not honor DESTDIR or equivalent for installing into a chroot.... 

the sad result is that linux distributions will need to pretty heavily patch the makefiles (example: https://github.com/clearlinux-pkgs/QAT-ZSTD-Plugin/blob/main/prefix.patch  ) in order to make the software packaging friendly.

**Comment by GarenJian-Intel** [comment]
@fenrus75  can you create a PR in the corresponding inner source repo so we can review your suggestion?

**Comment by fenrus75** [comment]
oh apologies I mistook this project for an open source project

(which aren't supposed to have internal repos anymore)

**Comment by GarenJian-Intel** [comment]
No problem. Please create PR there. I will close this issue.
