### ISSUE TITLE
Benchmark tool fails when built with QATLib on AlmaLinux 8.8 VM with Intel Xeon Platinum 8481C

### ISSUE THREAD

**Issue by ramkumarpvs** [intel/QAT-ZSTD-Plugin#7]
Hi,
We have built benchmark tool using QATLib(inTree) and we are seeing issue when we run benchmark tool.
While using QATLib intree mode, do we need to install QAT driver , start service and update any config?

We have also attempted to compile with **make benchmark ENABLE_USDM_DRV=1** and run the test. It still failed with same error.

**Environment:**
QAT-ZSTD-Plugin latest master.
QATLib latest master.
Zstd 1.5.5
AlmaLinux 8.8 VM in GCP instance (Machine c3-standard-8, CPU: Intel Sapphire Rapids)
Intel Xeon Platinum 8481C

**Test**:  All default parameters. The testfile is ~42KB
./benchmark testfile

**Error:**
Compress failed
ZSTDErrorString(res): Block-level external sequence producer returned an error code

**Comment by ramkumarpvs** [comment]
Any inputs here ?

**Comment by GarenJian-Intel** [comment]
Hi, you can "make benchmark ENABLE_USDM_DRV=1 DEBUGLEVEL=2" to get more error info.

**Comment by ramkumarpvs** [comment]
This is with Debug enabled.

```
qatseqprod.c: There is no QAT device available, please check QAT device status
qatseqprod.c: InitStatus: -1
.Compress Chunk size 32768
.qatseqprod.c: The hardware was not successfully started
.Compress failed
ZSTDErrorString(res): Block-level external sequence producer returned an error code
```

**Comment by GarenJian-Intel** [comment]
If your machine has QAT device, it must be driver issue.
Please check the installation of the driver, and make sure their sample-code can run.

**Comment by GarenJian-Intel** [comment]
Close it since no new reply.
